In [1]:
import numpy as np
import copy
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from matplotlib.patches import Rectangle

In [2]:
colors = mcolors.XKCD_COLORS
sort_colors = True

if sort_colors is True:
    names = sorted(
        colors, key=lambda c: tuple(mcolors.rgb_to_hsv(mcolors.to_rgb(c))))
else:
    names = list(colors)

replace_figure = False

f = open("README.md", "w")

cell1 = " view "
fix_cell1 = ""
i = 0
while i < 71:
    try:
        fix_cell1 = fix_cell1 + cell1[i]
    except:
        fix_cell1 = fix_cell1 + " "
    i += 1
cell2 = "name"
fix_cell2 = ""
i = 0
while i < 33:
    try:
        fix_cell2 = fix_cell2 + cell2[i]
    except:
        fix_cell2 = fix_cell2 + " "
    i += 1
cell3 = "RGB"
fix_cell3 = ""
i = 0
while i < 19:
    try:
        fix_cell3 = fix_cell3 + cell3[i]
    except:
        fix_cell3 = fix_cell3 + " "
    i += 1
f.write("|" + fix_cell1 + " | " + fix_cell2 + " | " + fix_cell3 + " | \n")

fix_cell1 = ""
i = 0
while i < 71:
    fix_cell1 = fix_cell1 + "-"
    i += 1
fix_cell2 = ""
i = 0
while i < 33:
    fix_cell2 = fix_cell2 + "-"
    i += 1
fix_cell3 = ""
i = 0
while i < 19:
    fix_cell3 = fix_cell3 + "-"
    i += 1
f.write("|" + fix_cell1 + " | " + fix_cell2 + " | " + fix_cell3 + " | \n")

for i, name in enumerate(names):
    file_name = name.split(' ')[0][5:]
    if len(name.split(' ')) > 1:
        for sub in name.split(' ')[1:]:
            file_name = file_name + '_' + sub
    file_name = file_name.replace("/", "-")

    if replace_figure:
        fig = plt.figure(figsize=(2, 0.3), dpi=30)
        ax = fig.add_subplot(111)
        rect1 = Rectangle((0, 0), 100, 25,
                          color=name, edgecolor = None)
        ax.add_patch(rect1)
        ax.yaxis.set_visible(False)
        ax.xaxis.set_visible(False)
        ax.set_axis_off()
        plt.subplots_adjust(top = 1, bottom = 0,
                            right = 1, left = 0,
                            hspace = 0, wspace = 0)
        plt.margins(0,0)
        plt.savefig("view/"+file_name+".png",
                    pad_inches = 0)
        plt.close()

    cell1 = "!["+name+"](view/"+file_name+".png)"
    fix_cell1 = ""
    i = 0
    while i < 71:
        try:
            fix_cell1 = fix_cell1 + cell1[i]
        except:
            fix_cell1 = fix_cell1 + " "
        i += 1
    cell2 = name
    fix_cell2 = ""
    i = 0
    while i < 33:
        try:
            fix_cell2 = fix_cell2 + cell2[i]
        except:
            fix_cell2 = fix_cell2 + " "
        i += 1

    R, G, B = mcolors.to_rgb(name)
    fix_cell3 = str(np.round(R,3)) + "  " + str(np.round(G,3)) + "  " + str(np.round(B,3))

    f.write("|" + fix_cell1 + " | " + fix_cell2 +  " | " + fix_cell3 + "| \n")
f.close()

In [3]:
previous_colors = {
  "myblue": [0.0, 0.588, 0.694],
  "mydarkblue": [0.008, 0.294, 0.478],
  "mycyan": [0.267, 0.718, 0.761],
  "myorange": [1.0, 0.682, 0.286],
}
for color in previous_colors:
    R1, G1, B1 = previous_colors[color]
    min_diff = 1
    for i, name in enumerate(names):
        R2, G2, B2 = mcolors.to_rgb(name)
        diff = np.sqrt((R1-R2)**2+(G1-G2)**2+(B1-B2)**2)
        if diff < min_diff:
            min_diff = copy.deepcopy(diff)
            closest_color = name
            closest_RGB = np.array([R2, G2, B2])
    print("closest color for", color, "is", closest_color, "with a diff", np.round(min_diff,3))
    print(np.array([R1, G1, B1]), " -- ", np.round(closest_RGB,3))


closest color for myblue is xkcd:teal blue with a diff 0.089
[0.    0.588 0.694]  --  [0.004 0.533 0.624]
closest color for mydarkblue is xkcd:prussian blue with a diff 0.027
[0.008 0.294 0.478]  --  [0.    0.271 0.467]
closest color for mycyan is xkcd:tealish with a diff 0.163
[0.267 0.718 0.761]  --  [0.141 0.737 0.659]
closest color for myorange is xkcd:butterscotch with a diff 0.016
[1.    0.682 0.286]  --  [0.992 0.694 0.278]
